
import sys
sys.path.insert(1, "../../")
from helper import MantidGeom

# using metre as unit
instrumentName = 'D11'
validFrom = "2017-10-01 23:59:59"
moderator_source = -2.0
# factor: 1, 2
factor = 2
# definition of the quadratic detector
numberPixelsVertical = 128 * factor
numberPixelsHorizontal = 128 * factor
# definition of a quadratic pixel
pixelName = "pixel"
pixelWidth = 0.0075 / factor
pixelHeight = 0.0075 / factor
x = pixelWidth / 2.
y = pixelHeight / 2.
z = 0.
thickness = repr(-0.0001)
# rear detector
zPos = 1.2
# start identification numbers
id0 = repr(0)
# rectangular detector
xstart = repr(-pixelWidth * (numberPixelsHorizontal - 1) / 2)
xstep = repr(pixelWidth)
xpixels = repr(numberPixelsHorizontal)
ystart = repr(-pixelHeight * (numberPixelsVertical - 1) / 2)
ystep = repr(pixelHeight)
ypixels = repr(numberPixelsVertical)
# Choose either FF = "x", SR = repr(numberPixelsRearHorizontal) or FF = "y", SR = repr(numberPixelsRearVertical)
FF = "y"  # idfillbyfirst
SR = repr(numberPixelsVertical)  #idstepbyrow
detector0 = "detector"

comment = """ This is the instrument definition file of the D11 Lowest momentum transfer & lowest background
       small-angle neutron scattering instrument at the ILL.
       Generated file, PLEASE DO NOT EDIT THIS FILE!
       This file was automatically generated by mantidgeometry/ILL/IDF/d11_generateIDF.py

       z axis defines the direction of the beam
       y axis will be the axis used for rotation
       coordinate system is right-handed

       y axis rotation defined by theta
       x axis rotation defined by phi
       z axis rotation defined by chi

       width x direction, height y direction

       Monochromator
       Incident wavelength 4.5 Angstrom <= wavelength <= 40 Angstrom
       Maximum wavelength at maximum detector distance of 39 m is 22 Angstrom
       Selector rotation normal to beam -7 deg to 7 deg
       Maximum wavelength at rotation -7 deg is 3.2 Angstrom

       Collimation
       11 guide sections
       Guide cross-section of 50 mm x 30 mm over 6.5 m
        Straight guide        50 mm x 45 mm over 28 m
                              50 mm x 45 mm -> 35 mm x 31.5 mm over 4 m
       Guide-to-sample distances are 1.5 m; 2.5 m; 4.0 m; 5.5 m; 8.0 m; 10.5 m; 13.5 m; 13.5 m; 16.5 m; 20.5 m; 28.0 m;
        34.0 m; 40.5 m;

       Sample
       Default sample dimension is 10 mm x 10 mm

       Multi-detector
       Sample-detector distances range from 1.2 m to 39 m
       Size 960 mm x 960 mm
       Pixel size 7.5 mm x 7.5 mm ( 128 x 128 pixels )

       For more information, please visit
       https://www.ill.eu/instruments-support/instruments-groups/instruments/d11/characteristics/
       """
d11 = MantidGeom(instrumentName, comment=comment, valid_from=validFrom)
d11.addSnsDefaults()
d11.addComment("SOURCE")
d11.addComponentILL("moderator", 0., 0., moderator_source, "Source")
d11.addComment("Sample position")
d11.addComponentILL("sample_position", 0., 0., 0., "SamplePos")
d11.addComment("DETECTOR")
d11.addComponentRectangularDetector(detector0, 0., 0., zPos, idstart=id0, idfillbyfirst=FF, idstepbyrow=SR)
d11.addRectangularDetector(detector0, pixelName, xstart, xstep, xpixels, ystart, ystep, ypixels)
d11.addComment("PIXEL, EACH PIXEL IS A DETECTOR")
d11.addCuboidPixel(pixelName, [-x, -y, z], [x, y, z], [-x, -y, thickness], [x, -y, z], shape_id="pixel-shape")
