import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.abspath(""))
from helper import MantidGeom

# Fermi chopper position (treated as source for TOF)
source = -0.48

# 2 Monitors
zMon1 = -1.3
zMon2 = 1.5


# distance between the sample and detectors:
rSampleDetectors = 1.5177 # distance from the sample of detectors with odd IDs
minTwoTheta = 0
maxTwoTheta = 136


# definition of a pixel
tubeRadius = 0.01252
tubeHeight = 0.25


#######
# PSD #
#######
number_pixels_per_tube = 128
pixel_height = tubeHeight/number_pixels_per_tube


###################################
# number of banks,tubes,detectors #
##################################
number_of_banks = 3
number_of_double_tubes_per_bank = 22
number_of_tubes_per_bank = 2*number_of_double_tubes_per_bank
numberDetectors = number_of_banks*number_of_tubes_per_bank*number_pixels_per_tube


 
#offset angle for position of the bank:
bank_offset_angle = 22

comment = """ This is the instrument definition file of the d007 diffuse scattering spectrometer at the ILL.
       Generated file, PLEASE DO NOT EDIT THIS FILE!
       This file was automatically generated by mantidgeometry/ILL/IDF/d007
    _generateIDF.py
       The generating script should be run as:
       python3 ./ILL/IDF/d007_generateIDF.py

       z axis defines the direction of the beam
       y axis will be the axis used for rotation
       coordinate system is right-handed
       x axis rotation defined by phi 
       y axis rotation defined by theta 
       height y direction
       The instrument operates in two modes
       - Diffraction:
          - wavelength 3.1 A, qmin = 0.4, qmax = 4.0
          - wavelength 4.8 A, qmin = 0.3, qmax = 2.5
          - wavelength 5.7 A, qmin = 0.2, qmax = 2.1
       - Spectroscopy time-of-flight 
          - using Fermi chopper, with the same possible wavelengths

       Source-to-sample distance is 0.48 m
       Three detector banks with 22 position-sensitive He3 detectors each
       Each position-sensitive He3 detectors is a double tube
            with 128 pixels per tube 
       Each bank has thus 44 tubes of 128 pixels (numberred from left to right and bottom to top)
       Each detector is located 1.51 m from the sample
       covering 2 Theta range from about 10 to 155 degrees
       Detector tubes have a 19.53mmx10mm rectangular section and are 250 mm in height
       For more information, please visit 
       https://www.ill.eu/instruments-support/instruments-groups/instruments/d007
    /characteristics/
       """

instrument_name = "D007"
valid_from = "2025-01-01 00:00:00"
last_modified = time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime())

d007 = MantidGeom(instrument_name, comment=comment, valid_from=valid_from)
d007.addSnsDefaults(default_view="3D", axis_view_3d="z-", theta_sign_axis="x")


##THE ANGLES ARE DEFINED IN DEGREES, AND LENGTHS IN METERS##

##########
# Source #
##########
d007.addComment("SOURCE")
d007.addComponentILL("source", 0.0, 0.0, source, "Source")

##########
# Sample #
##########
d007.addComment("SAMPLE")
d007.addComponentILL("sample_position", 0.0, 0.0, 0.0, "SamplePos")

###########
# Monitors #
###########
d007.addComment("MONITORS")
d007.addMonitors(names=["monitor1", "monitor2"], distance=[zMon1, zMon2])
d007.addComment("MONITOR SHAPE")
d007.addComment("FIXME: Do something real here.")
d007.addDummyMonitor(0.01, 0.03)
d007.addComment("MONITOR IDs")
d007.addMonitorIds([repr(100000), repr(100001)])


# Placement centre of bank:
detector = d007.addComponent("detector", name="detector", idlist="detector_ids", blank_location=True)
d007.addLocation(root=detector, x=repr(0.0), y=repr(0.0), z=repr(0.0))
d007.addDetectorIds("detector_ids", [1, numberDetectors, 1])

# Define position of different banks:
totalbank = d007.makeTypeElement("detector")
for f in range(number_of_banks):
    bank = d007.addComponent("bank", root=totalbank, name=f"bank{2+f}")
    d007.addLocation(root=bank, x = 0, y = 0, z = 0, rot_y = repr(-(bank_offset_angle+47*(f))), name=f"bank{2+f}")



# The negative rot_y  angle rotates the coordinate system associated to the bank and in particular reverse the y axis
# all the rotations in this system for the tube location will therefore need to be with negative angles
# to appear in the instrument viewer with a positive angle  


# Define position of tubes in reference to a bank:
bank = d007.makeTypeElement("bank")
thetatube=-21
tube = d007.addComponent("tube", root=bank)
for i in range(number_of_tubes_per_bank):
   theta = -(thetatube+0.38) if i%2 else -(thetatube-0.38)
   d007.addLocationPolar(root=tube, r=repr(rSampleDetectors), theta=repr(theta), phi=repr(0), name=f"tube_{i + 1}")
   thetatube += (2 if i%2 else 0)

# Define different pixel positions in a tube:
tube_bottom_pos = -pixel_height*number_pixels_per_tube/2.0
tube_top_pos = pixel_height*number_pixels_per_tube/2.0
pixel_positions = np.linspace(tube_bottom_pos, tube_top_pos, number_pixels_per_tube)
tube = d007.makeTypeElement("tube")
pixel = d007.addComponent("pixel", root=tube)
for l in range(number_pixels_per_tube):
   pixel_position= (tube_bottom_pos + pixel_height/2)  + l* pixel_height
   d007.addLocation(root=pixel, x=0, y=pixel_position, z=0, name=f"pixel_{ l+1}")


#Define PSD cuboid pixels:
pixelWidth =0.01953
x = pixelWidth / 2.
y = pixel_height / 2.
z = 0.
thickness = 0.005

d007.addCuboidPixel("pixel", [-x, -y, thickness/2.], [-x, y, thickness/2.], [-x, -y, -thickness/2.], [x, -y, thickness/2.], shape_id="pixel-shape")



d007.writeGeom(instrument_name + "_Definition.xml")
