from __future__ import (absolute_import, division, print_function)

import sys

sys.path.insert(1, "../../")
from helper import MantidGeom

# using metre as unit
instrumentName = 'Figaro'
validFrom = "2017-01-31 23:59:59"
numberOfTubes = 64
pixelWidth = 0.0074
detectorWidth = pixelWidth * numberOfTubes
numberOfPixelsPerTube = 256
pixelHeight = 0.0012
detectorHeight = pixelHeight * numberOfPixelsPerTube
zSource = -5.497 # Chopperpair centre. Will be changed by the LoadILLReflectometry.
zDetector = 1.0  # minimum default sample - detector distance
# 2 Monitors
zMon1 = 0.0181  # ?
zMon2 = -0.338  # from Nexus file Theta.monitor2_position
# definition of the rectangular detector
# ATM the pixel counts are integrated over the horizontal rows.
xstart = repr(0)
xstep = repr(pixelWidth * numberOfTubes)
xpixels = repr(1)
ystart = repr(-detectorHeight / 2 + pixelHeight / 2)
ystep = repr(pixelHeight)
ypixels = repr(numberOfPixelsPerTube)
# definition of a cuboid pixel
x = detectorWidth / 2
y = pixelHeight / 2
z = pixelWidth / 2
# 2 precision slits (only centre points along z are defined!)
slit2Centre = -2.53
slit3Centre = -0.368

comment = """ This is the instrument definition file of the figaro reflectometer at the ILL.
       Generated file, PLEASE DO NOT EDIT THIS FILE!
       This file was automatically generated by mandidgeometry/ILL/IDF/figaro_generatorIDF.py

       z axis defines the direction of the direct beam
       y axis will be the axis used for rotation in the LoadILLReflectometry algorithm
       coordinate system is right-handed

       y axis rotation defined by theta
       x axis rotation defined by phi
       z axis rotation defined by chi

       ILL 3He tubular Aluminium monoblock - width x direction, height y direction

       Incident wavelength range 2 - 30 Angstroms

       The multitube detector is of size 500 mm x 250 mm and flat, its shape is rectangular
       Its resolution is 7 mm x 2 mm
       Sample-detector distance is 1.0 m - 2.8 m (3 m in text)
       Dead-time 34 ns

       It consists of 64 horizontal tubes, each has a height of 7.4 mm
       It consists of 256 pixels, each about 1.2 mm wide

       Beam area at sample position 40 mm x 10 mm (width x height)
       Scattering plane is vertical
       Q-range, up   0.0045 - 0.42 A-1
       Q-range, down 0.0045 - 0.27 A-1

       For more information, please visit
       https://www.ill.eu/instruments-support/instruments-groups/instruments/figaro/characteristics/
       """
figaro = MantidGeom(instrumentName, comment=comment, valid_from=validFrom)
figaro.addSnsDefaults()
figaro.addComment("SOURCE")
figaro.addComponentILL("chopper1", 0.0, 0.0, zSource, "Source")
figaro.addComment("Sample position")
figaro.addComponentILL("sample_position", 0.0, 0.0, 0.0, "SamplePos")
figaro.addComment("MONITORS")
figaro.addMonitors(names=["monitor1", "monitor2"], distance=[zMon1, zMon2])
figaro.addComment("MONITOR SHAPE")
figaro.addComment("FIXME: Do something real here.")
figaro.addDummyMonitor(0.01, 0.03)
figaro.addComment("MONITOR IDs")
figaro.addMonitorIds(["100000", "100001"])
figaro.addComment("2 Slits")
figaro.addComponentILL("slit2", 0.0, 0.0, slit2Centre)
figaro.addComponentILL("slit3", 0.0, 0.0, slit3Centre)
figaro.addComment("DETECTORS")
figaro.addComment("64 tubes form the detector")
figaro.addComponentRectangularDetector("detector", 0.0, 0.0, zDetector, idstart="1", idfillbyfirst="x",
                                    idstepbyrow="1")
figaro.addComment("PIXEL, EACH PIXEL IS A DETECTOR")
figaro.addRectangularDetector("detector", "pixel", xstart, xstep, xpixels, ystart, ystep, ypixels)
figaro.addCuboidPixel("pixel", [-x, -y, z], [x, y, z], [-x, -y, -z], [x, -y, z], shape_id="pixel-shape")
figaro.showGeom()
