import os
import sys
from lxml import etree as le
import numpy as np
import argparse
sys.path.insert(0, os.path.normpath(os.path.dirname(__file__)) + "/../../")
from helper import MantidGeom

parser = argparse.ArgumentParser()
parser.add_argument('--TubeHeight', help='Tube height in meters', default=1.92)
parser.add_argument('--EquatorialPixel', help='The index of the pixel (counting from 1) which is in xz plane', default=80)
parser.add_argument('--GlobalRotationAngle', help='The global offset angle in degrees', default = 0.)
args = parser.parse_args()

valid_from = "1901-01-01 00:00:00"
# All distances are in meter, angles in degrees
instrumentName = 'PANTHER'
numberOfBoxes = 9
numberOfTubesPerBox = 32
numberOfTubes = numberOfBoxes * numberOfTubesPerBox
numberOfPixelsPerTube = 256
firstDetectorId = 1
l1 = 0.8
l2 = 2.5
pixelRadius = 0.022 / 2. - 0.0004
tubeHeight = float(args.TubeHeight)
equator = float(args.EquatorialPixel)
pixelHeight = tubeHeight / numberOfPixelsPerTube
tubeVerticalShift = (numberOfPixelsPerTube / 2 - equator) * pixelHeight
monitorZ = -0.533

boxGapAngle = 1.03
boxAngleWidth = 16.06
tubeAngleStep = boxAngleWidth / (numberOfTubesPerBox - 1)

boxAngles = list()
firstBoxCenterAngle = -0.5 * (boxAngleWidth + boxGapAngle)
for i in range(numberOfBoxes):
    boxAngles.append(firstBoxCenterAngle + i * (boxAngleWidth + boxGapAngle))

comment = """ This is the instrument definition file of the PANTHER spectrometer at the ILL.
       Generated file, PLEASE DO NOT EDIT THIS FILE!
       This file was automatically generated by mantidgeometry/ILL/IDF/panther_generateIDF.py
       """
geometry = MantidGeom(instrumentName, comment=comment, valid_from=valid_from)
geometry.addSnsDefaults(theta_sign_axis='x')
geometry.addComponentILL('fermi_chopper', 0.0, 0.0, -l1, 'Source')
geometry.addComponentILL('sample-position', 0.0, 0.0, 0.0, 'SamplePos')
geometry.addMonitors(names=['monitor'], distance=[monitorZ])
geometry.addDummyMonitor(0.009, 0.036) # the real radius is 0.09
geometry.addMonitorIds(['100000'])
geometry.addCylinderPixelAdvanced(
    'pixel', center_bottom_base={'x': 0., 'y': -pixelHeight / 2., 'z': 0.},
    axis={'x': 0., 'y': 1., 'z': 0.}, pixel_radius=pixelRadius,
    pixel_height=pixelHeight,
    algebra='pixel_shape')
root = geometry.getRoot()
detectorType = le.SubElement(root, 'type', name='detector')
tubes = le.SubElement(detectorType, 'component', type='tube')
for boxIndex, boxAngle in enumerate(boxAngles):
    for tubeIndex in range(numberOfTubesPerBox):
        tubeAngle = boxAngle - boxAngleWidth / 2. + tubeIndex * tubeAngleStep
        x = l2 * np.sin(np.deg2rad(tubeAngle))
        z = l2 * np.cos(np.deg2rad(tubeAngle))
        attributes = {
            'x': str(x),
            'y': str(0.),
            'z': str(z),
            'name': 'tube_{}'.format(boxIndex * numberOfTubesPerBox + tubeIndex + 1)
        }
        le.SubElement(tubes, 'location', **attributes)
tubeType = le.SubElement(root, 'type', name='tube', outline='yes')
tube = le.SubElement(tubeType, 'component', type='pixel')
tube_bottom_pos = -(equator - 1) * pixelHeight
tube_top_pos = (numberOfPixelsPerTube - equator) * pixelHeight
pixelPositions = np.linspace(tube_bottom_pos, tube_top_pos, numberOfPixelsPerTube)
for i, pos in enumerate(pixelPositions):
    le.SubElement(tube, 'location', y=str(pos), name='pixel_{}'.format(i + 1))
detector = geometry.addComponent('detector', idlist='detectors')
le.SubElement(detector, 'location')
geometry.addDetectorIds('detectors', [1, 73728, None])
geometry.writeGeom("./ILL/IDF/" + instrumentName + "_Definition.xml")
