from __future__ import (absolute_import, division, print_function)

import os
path = os.path.abspath("")
import sys
sys.path.insert(0, path)
from helper import MantidGeom

# Metre is the unit
instrument_name = 'SAM'
valid_from = "2024-01-01 00:00:00"
moderator_source = -2.0

#  Monitor distance
z_monitor = -16.7

# definition of the quadratic detector
number_pixels_vertical = 128
number_pixels_horizontal = 256

# definition of a quadratic pixel
pixel_name = "pixel"
pixel_width = 0.0025
pixel_height = 0.005
x = pixel_width / 2.0
y = pixel_height / 2.0
z = 0.
thickness = 0.0001

# rear detector
zPos = 0.0

# start identification numbers
id0 = repr(0)

# rectangular detector
xstart = repr(pixel_width * (number_pixels_horizontal - 1) / 2)
xstep = repr(-pixel_width)
xpixels = repr(number_pixels_horizontal)
ystart = repr(-pixel_height * (number_pixels_vertical - 1) / 2)
ystep = repr(pixel_height)
ypixels = repr(number_pixels_vertical)

FF = "y"
SR = repr(number_pixels_horizontal)

detector0 = "detector"

comment = """ This is the instrument definition file of the SAM small-angle neutron scattering instrument at the ILL.
       Generated file, PLEASE DO NOT EDIT THIS FILE!
       This file was automatically generated by mantidgeometry/ILL/IDF/d11_generateIDF.py

       z axis defines the direction of the beam
       y axis will be the axis used for rotation
       coordinate system is right-handed

       y axis rotation defined by theta
       x axis rotation defined by phi
       z axis rotation defined by chi

       width x direction, height y direction

       Monochromator
       Incident wavelength 4.5 Angstrom <= wavelength <= 40 Angstrom
       Maximum wavelength at maximum detector distance of 39 m is 22 Angstrom
       Selector rotation normal to beam -7 deg to 7 deg
       Maximum wavelength at rotation -7 deg is 3.2 Angstrom

       Collimation
       11 guide sections
       Guide cross-section of 50 mm x 30 mm over 6.5 m
        Straight guide        50 mm x 45 mm over 28 m
                              50 mm x 45 mm -> 35 mm x 31.5 mm over 4 m
       Guide-to-sample distances are 1.5 m; 2.5 m; 4.0 m; 5.5 m; 8.0 m; 10.5 m; 13.5 m; 13.5 m; 16.5 m; 20.5 m; 28.0 m;
        34.0 m; 40.5 m;

       Sample
       Default sample dimension is 10 mm x 10 mm

       Multi-detector
       Sample-detector distances range from 1.2 m to 39 m
       Size 960 mm x 960 mm
       Pixel size 7.5 mm x 7.5 mm ( 128 x 128 pixels )

       For more information, please visit
       https://www.ill.eu/instruments-support/instruments-groups/instruments/d11/characteristics/
       """
sam = MantidGeom(instrument_name, comment=comment, valid_from=valid_from)
sam.addSnsDefaults(default_view='3D', axis_view_3d='z-')
sam.addComment("SOURCE")
sam.addComponentILL("moderator", 0., 0., moderator_source, "Source")
sam.addComment("Sample position")
sam.addComponentILL("sample_position", 0., 0., 0., "SamplePos")
sam.addComment("MONITORS")
sam.addMonitors(names=["monitor1"], distance=[z_monitor])
sam.addDummyMonitor(0.01, 0.03)
sam.addComment("MONITOR IDs")
sam.addMonitorIds([repr(100000)])
sam.addComment("DETECTOR")
sam.addComponentRectangularDetector(detector0, 0., 0., zPos, idstart=id0, idfillbyfirst=FF, idstepbyrow=SR)
sam.addRectangularDetector(detector0, pixel_name, xstart, xstep, xpixels, ystart, ystep, ypixels)
sam.addComment("PIXEL, EACH PIXEL IS A DETECTOR")
sam.addCuboidPixel(
    pixel_name,
    [-x, -y, thickness/2.],
    [-x, y, thickness/2.],
    [-x, -y, -thickness/2.],
    [x, -y, thickness/2.],
    shape_id="pixel-shape")
sam.writeGeom(instrument_name + "_Definition.xml")
